#!/bin/bash
# Create .config for testing in Travis CI
set -eu

echo "export DB_USER=test" > .config
echo "export DB_PASSWORD=test" >> .config
echo "export PORT=5432" >> .config
echo "export POSTGRES_PASSWORD=postgres" >> .config
