#!/bin/bash
set -eu

source .config
source test/functions.sh
URL=$(bin/construct-url)

main() {
    if psql $URL -l &> /dev/null; then
	echo_success "PASSED: the user $DB_USER can access the database"
    else
	echo_failure "FAILED: the user $DB_USER cannot access the database using $URL"
	exit 1
    fi
}


main
