#!/bin/bash
#
# Test that database user is read only and cannot create new tables.
set -eu

source .config
source test/functions.sh
URL=$(bin/construct-url)

create_table() {
    psql $URL -c "CREATE TABLE new_table (column1 INT);"
}

main() {
    local message
    message=$(create_table 2>&1) || : # having || : let's us use set -eu

    if echo $message | grep -q "permission denied for schema public"; then
	echo_success "PASSED: the user $DB_USER has read-only privilege"
	exit 0
    elif echo $message | grep -q "CREATE TABLE"; then
	echo_failure "FAILED: the user $DB_USER can create tables"
	exit 1
    else
	echo_failure "FAILED: some other problem occurred when testing for read-only privilege"
	echo_failure "See message below:"
	echo $message
	exit 1
    fi
}


main
