#!/bin/bash
#
# Attempt to access the database with the postgres admin account.
set -eu

URL_ADMIN=$(bin/construct-url --admin)

list_tables() {
    psql -l $URL_ADMIN
}

main() {
    local message
    message=$(list_tables 2>&1) || : # having || : let's us use set -eu

    if echo $message | grep -q "no pg_hba.conf entry"; then
	echo "Postgres admin user cannot access the database"
    else
	echo "Failed to prevent locking the database"
    fi
}


main
