#!/bin/bash
#
# Test that DB_USER can select tables and that they are populated.
set -eu

URL=$(bin/construct-url)

query_db() {
    psql $URL -c "SELECT * FROM $1 LIMIT 5;" &> /dev/null
}

count_rows() {
    psql -t $URL -c "SELECT COUNT(*) FROM $1;" 2>&1
}

test_select() {
    if query_db $1; then
	echo "Successfully queried $1 table!"
    else
	echo "Failed to query $1 table"
	exit 1
    fi
}

test_table_populated() {
    if [[ $(count_rows $1) -gt 0 ]]; then
	echo "$1 table is populated!"
    else
	echo "$1 table is not populated"
	exit 1
    fi
}

main() {
    test_select wells
    test_table_populated wells
    test_table_populated states
    test_table_populated counties
}


main
