language: bash

services:
  - docker

before_install:
  - echo "export DB_USER=docker" > .config
  - echo "export DB_PASSWORD=docker" >> .config
  - echo "export PORT=5432" >> .config
  - echo "export POSTGRES_PASSWORD=postgres" >> .config
  - docker build -t wells .
  - docker run --rm -p 5432:5432 wells
  - docker ps -a
  - sleep 5

script:
  - test/test-db
