language: python

services:
  - docker

before_install:
  - echo "DB_USER=test" > .config
  - echo "DB_PASSWORD=test" >> .config
  - echo "PORT=5432" >> .config
  - echo "POSTGRES_PASSWORD=test" >> .config
  - docker build -t wells .
  - docker run --rm -d -p 5432:5432 wells

script:
  - bin/test-db
