language: bash

services:
  - docker

before_install:
  - echo "export DB_USER=test" > .config
  - echo "export DB_PASSWORD=test" >> .config
  - echo "export PORT=5432" >> .config
  - echo "export POSTGRES_PASSWORD=test" >> .config
  - docker build -t wells .
  - docker run --rm -d -p 5432:5432 wells
  - docker ps -a

script:
  - test/test-db
